spring.profiles.active: devel

server.port: 9000

spring.datasource:
    url: jdbc:mysql://localhost:3306/spring_blog?useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: devel
    password: devel

spring.jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.jade4j:
    caching: false