spring.profiles.active: dev

server.port: 9000

spring.datasource:
    url: jdbc:mysql://localhost:3306/spring_blog?useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: devel
    password: devel

spring.thymeleaf:
    cache: false

spring.jade4j:
    caching: false

spring.jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    #hbm2ddl.auto: update

spring.redis:
    host: localhost
    port: 6379
